# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=2)),
                ('dates', models.TextField()),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('relation', models.CharField(max_length=15)),
                ('purpose', models.TextField()),
                ('hostelsavailable', models.CharField(max_length=25)),
            ],
        ),
    ]
