# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='dates',
        ),
        migrations.AddField(
            model_name='detail',
            name='Indate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='Outdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
