# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20170327_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('roll_number', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('device_id', models.CharField(blank=True, default='none', max_length=1000)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Indate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='Outdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='hostelsavailable',
            field=models.CharField(max_length=10),
        ),
    ]
