# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20170328_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
